---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmGlobals:
  chartHome: ../../../charts

helmCharts:
  - name: capi-management
    releaseName: capi-management
    valuesFile: values.yaml